name: Build, Test and Deploy Static Site

on:
  push:
    branches:
      - release
  workflow_dispatch:

jobs:
  release:
    container: alpine:latest
    env:
      HOME: /root
    runs-on: ubuntu-latest
    steps:
      - name: Setup Alpine
        run: apk add --no-cache git bash curl sudo bubblewrap alpine-sdk
      - name: Configure git safedir properly
        run: git config --global --add safe.directory $(pwd)
      - uses: actions/checkout@v6
      - name: Install dune
        uses: ocaml-dune/setup-dune@v1
        with:
          steps: "install-dune"
      - name: Install depexts
        run: |
          DEPEXTS="$(dune show depexts)"
          apk add $DEPEXTS
      # HACK: to setup everything needed to build compiler?
      - uses: ocaml/setup-ocaml@v3
        with:
          cache-prefix: v1
          ocaml-compiler: 5.4.0
      - name: Build and test
        uses: ocaml-dune/setup-dune@v1
        with:
          steps: "build runtest"
      - name: Make artifact
        run: bash scripts/make-artifact.sh
      - uses: actions/upload-artifact@v4
        with:
          name: elfeed-offline-x86-artifact
          path: elfeed-offline.tar.gz
